image: openjdk:8-jdk
variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS: "26.1.1"

stages:
 - build

before_script:
  - source /home/public/android-sdk-linux/initAndroid.sh -s ${ANDROID_COMPILE_SDK} -b ${ANDROID_BUILD_TOOLS}


build_debug:
  stage: build
  script:
    - /./home/public/gitrunner/changeAppVersion.sh app/build.gradle " $CI_COMMIT_REF_NAME\_$CI_PIPELINE_ID" --append
    - ./gradlew assembleNormalDebug --stacktrace
  artifacts:
    paths:
    - app/build/outputs/apk/normal/debug/*.apk
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/

build_release:
  stage: build
  script:
   - ./gradlew clean check assembleNormalRelease --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
  artifacts:
    paths:
    - app/build/outputs/apk/normal/release/*.apk
    - app/build/outputs/mapping/normal/release/mapping.txt
  only:
    - master

build_fdroid:
  stage: build
  script:
    - ./gradlew clean check assembleAdblockerRelease --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
  artifacts:
    paths:
      - app/build/outputs/apk/adblocker/release/*.apk
      - app/build/outputs/mapping/adblocker/release/mapping.txt
  only:
    - master
