image: openjdk:8-jdk
variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_SDK_TOOLS: "26.1.1"

stages:
 - test
 - build

before_script:
  - source /home/public/android-sdk-linux/initAndroid.sh -s ${ANDROID_COMPILE_SDK}
  
build_debug:
  stage: build
  script:
    - /./home/public/gitrunner/changeAppVersion.sh app/build.gradle " $CI_COMMIT_REF_NAME\_$CI_PIPELINE_ID" --append
    - ./gradlew assembleNormalDebug --stacktrace -x test
  artifacts:
    paths:
    - app/build/outputs/apk/normal/debug/*.apk
  only:
    - translations


build_fdroid:
  stage: build
  script:
    - ./gradlew clean assembleAdblockerFdroid --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
  artifacts:
    paths:
      - app/build/outputs/apk/adblocker/fdroid/*.apk
      - app/build/outputs/mapping/adblocker/fdroid/mapping.txt
  only:
    - master

build_release:
  stage: build
  script:
   - ./gradlew clean assembleNormalRelease --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
  artifacts:
    paths:
    - app/build/outputs/apk/normal/release/*.apk
    - app/build/outputs/mapping/normal/release/mapping.txt
  only:
    - master

test_build_release:
  stage: test
  script:
    - ./gradlew clean assembleNormalUnsignedRelease --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
    - master