image: thyrlian/android-sdk

stages:
 - test
 - build

before_script:
  - chmod +x gradlew

build_debug:
  stage: build
  script:
    - ./changeVersion.sh app/build.gradle " $CI_COMMIT_REF_NAME\_$CI_PIPELINE_ID" --append
    - ./gradlew assembleNormalDebug --stacktrace -x test
  artifacts:
    paths:
    - app/build/outputs/apk/normal/debug/*.apk
  only:
    - translations


build_fdroid:
  stage: build
  script:
    - curl -o $KEYSTORE_FILE $KEYSTORE_URL
    - ./gradlew clean assembleAdblockerFdroid --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
  artifacts:
    paths:
      - app/build/outputs/apk/adblocker/fdroid/*.apk
      - app/build/outputs/mapping/adblocker/fdroid/mapping.txt
  only:
    - master

build_release:
  stage: build
  script:
   - curl -o $KEYSTORE_FILE $KEYSTORE_URL
   - ./gradlew clean assembleNormalRelease --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
  artifacts:
    paths:
    - app/build/outputs/apk/normal/release/*.apk
    - app/build/outputs/mapping/normal/release/mapping.txt
  only:
    - master

test_build_release:
  stage: test
  script:
    - ./gradlew clean assembleNormalUnsignedRelease --stacktrace -x test
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
    - master